on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  extract-args:
    runs-on: ubuntu-22.04
    steps:
      - shell: bash
        run: |
          TOTAL_JAVA_VERSION=$(cat ${{ inputs.file }} | grep "JAVA_VERSION" | cut -d'=' -f2)
          BASE_JAVA_VERSION=$(echo $TOTAL_JAVA_VERSION | cut -d'-' -f1)
          MAJOR_JAVA_VERSION=$(echo $BASE_JAVA_VERSION | cut -d'.' -f1)
          echo "IMAGE_TAGS=${{ inputs.image }}:$MAJOR_JAVA_VERSION,${{ inputs.image }}:$BASE_JAVA_VERSION,${{ inputs.image }}:$TOTAL_JAVA_VERSION" >> $GITHUB_ENV
          echo "ARGS_CONTENT=$(cat ${{ inputs.file }})" >> $GITHUB_ENV
      - shell: bash
        run: |
          echo "Image tags extracted: ${{ env.IMAGE_TAGS }}"
