name: build and validate
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with:
          args: dockerBuildImages

      - name: Scan java-11 image
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/java
          tag: 11
          category: java-11
          output-mode: github

      - name: Scan java-14 image
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/java
          tag: 14
          category: java-14
          output-mode: github
